# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/2024/01/Upgrade_online/flash_100t_test/flash_100t_test.srcs/sources_1/ip/fifo_1024x8/fifo_1024x8.xci
# IP: The module: 'fifo_1024x8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/2024/01/Upgrade_online/flash_100t_test/flash_100t_test.srcs/sources_1/ip/fifo_1024x8/fifo_1024x8.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_1024x8'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/2024/01/Upgrade_online/flash_100t_test/flash_100t_test.srcs/sources_1/ip/fifo_1024x8/fifo_1024x8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_1024x8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/2024/01/Upgrade_online/flash_100t_test/flash_100t_test.srcs/sources_1/ip/fifo_1024x8/fifo_1024x8.xci
# IP: The module: 'fifo_1024x8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/2024/01/Upgrade_online/flash_100t_test/flash_100t_test.srcs/sources_1/ip/fifo_1024x8/fifo_1024x8.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_1024x8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/2024/01/Upgrade_online/flash_100t_test/flash_100t_test.srcs/sources_1/ip/fifo_1024x8/fifo_1024x8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_1024x8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
